version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket codepipeline-us-east-2-588194207253 --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
