AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda
Resources:
  computePiLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: nodejs8.10
      CodeUri: ./lambdaCode
      Description: 'Lambda to compute pi'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::061753407487:role/LambdaRole'
      Events:
        getAZsAPI:
          Type: API
          Properties:
            Path: /getazs
            Method: get
      Enviroment:
        Variables:
          REGION: ap-southeast-2
